{% set version = "3.0.6" %}

package:
  name: pytest-spec
  version: {{ version }}

source:
  fn: pytest-spec-{{ version }}.tar.gz
  url: https://github.com/pchomik/pytest-spec/archive/{{ version }}.tar.gz
  sha256: 396f7d0aeed769b7566978cde5ef5765598d6139c8b47eb92709fe9561ee1c08

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - pytest
    - mock >=1.0.1

test:
  source_files:
    - test
  commands:
    - py.test test

about:
  home: https://github.com/pchomik/pytest-spec
  license: GPL-2.0
  license_family: GPL2
  license_file: LICENSE.txt
  summary: pytest plugin to display test execution output like a SPECIFICATION

  dev_url: https://github.com/pchomik/pytest-spec

extra:
  recipe-maintainers:
    - mcg1969
