{% set version = "3.0.4" %}

package:
  name: pytest-spec
  version: {{ version }}

source:
  fn: pytest-spec-{{ version }}.tar.gz
  url: https://github.com/pchomik/pytest-spec/archive/{{ version }}.tar.gz
  sha256: 488c1af458a60a494b9a37031061cf912ba49f5f5e502f204a2f986e86465148

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - pytest
    - mock >=1.0.1

test:
  source_files:
    - test
  commands:
    - py.test test

about:
  home: https://github.com/pchomik/pytest-spec
  license: GPL-2.0
  license_family: GPL2
  license_file: LICENSE.txt
  summary: pytest plugin to display test execution output like a SPECIFICATION

  dev_url: https://github.com/pchomik/pytest-spec

extra:
  recipe-maintainers:
    - mcg1969
