{% set name = "pytest-spec" %}
{% set version = "5.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7d8a7281bd86e20b8434e6a500cb4ce361595e04b9af5c84b08a50814c629b3f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - poetry
    - pip
  run:
    - python >=3.6
    - six

test:
  imports:
    - pytest_spec
    - test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pchomik/pytest-spec
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: LICENSE.txt
  summary: pytest plugin to display test execution output like a SPECIFICATION

  dev_url: https://github.com/pchomik/pytest-spec

extra:
  recipe-maintainers:
    - mcg1969
