{% set name = "pytest-spec" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-spec-{{ version }}.tar.gz
  sha256: 4af154588195f4bb6c62d6ca030a20218db7d80b675a08897d9a99239ea3d087

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - poetry
    - pip
  run:
    - python >=3.6
    - six

test:
  imports:
    - pytest_spec
    - test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pchomik/pytest-spec
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: LICENSE.txt
  summary: pytest plugin to display test execution output like a SPECIFICATION

  dev_url: https://github.com/pchomik/pytest-spec

extra:
  recipe-maintainers:
    - mcg1969
