travis:
  secure:
    BINSTAR_TOKEN: nkPrsFA+8Ik+lyG2Sz8MoHfqCwWPwdfTEGDIG0Ewqg8OF+4G+v8JB8l4eLPBYynLhpW7ScVbcVcyOi6VMW6T0K3qOmMaIN5XosARQLVtEoidz2BNs2PzKvCnmLANOec72ClNCtPv2QJTgHNRojo6ArBhOIFN3Un09ddwC2HcHBJyMe4Noo5pfAp+zdTGncHu6SVs7N60yid9WeA9o1VKsM5J1JGxSHQcTHh5fkgGPcpjuqfKFphyixZybHWPUBC+R9K/emVqv14bR+HFBtcn1Wu/oiDNy9EO9g19n47/YSMoFXT0sdwQsx8WuOdA8LJ4m3hsgPY/RYJX117A01nLrIZbagnlQTytQEqcBhLBf9DZ6B5rcD4jsNEOwJnDiY3AzIlhneixuQ1ZW16pkcNC5ck4+sVsv1fbBzTS8bDuXYwW+ZQxkYcXhXi2UX6lusOD4MdG8ofNpjrNYviPcUgGxUozIrFnx1/2Ff7dMAcgyxfXoIvAJD0tLZvCVtERZGs6pJ9jy424KVVzBQb/2CSO9QnP95EnEkdSRn3smE/GGhzKuGHAvB9QRWbdW7rZ1YgSPiEhvodIP4JF/yOd5QTA1uIHHiKrGWTCS8qz9vWLVbXMLiBVhKBH3+QevSgK1Z6tX/M4KA5sT0CygSgRQaFGfCwx4uouT8nmP0RfTO7IQ54=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
